using System.Text.Json;
using System.Text.Json.Serialization;

namespace MvcStructureInspector;

/// <summary>
/// Serializes / deserializes <see cref="ProjectSnapshot"/> to JSON so that
/// a previously inspected project can later be compared against a live project.
/// </summary>
public static class SnapshotSerializer
{
    private static readonly JsonSerializerOptions JsonOpts = new()
    {
        WriteIndented       = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.CamelCase) }
    };

    /// <summary>Persist a snapshot to a JSON file.</summary>
    public static void Save(ProjectSnapshot snapshot, string path)
    {
        SecurityGuard.AssertSafeOutputPath(path);
        string json = JsonSerializer.Serialize(snapshot, JsonOpts);
        File.WriteAllText(path, json, System.Text.Encoding.UTF8);
    }

    /// <summary>Reload a snapshot from a previously saved JSON file.</summary>
    public static ProjectSnapshot Load(string path)
    {
        if (!File.Exists(path))
            throw new FileNotFoundException($"Snapshot file not found: {path}");

        string json = File.ReadAllText(path);
        return JsonSerializer.Deserialize<ProjectSnapshot>(json, JsonOpts)
               ?? throw new InvalidOperationException("Failed to deserialize snapshot — file may be corrupt.");
    }

    /// <summary>
    /// Given a report path (either .txt or .snapshot.json), resolve the
    /// corresponding .snapshot.json path.
    /// </summary>
    public static string ResolveSnapshotPath(string reportPath)
    {
        string ext = Path.GetExtension(reportPath).ToLowerInvariant();

        if (ext == ".json" && reportPath.EndsWith(".snapshot.json", StringComparison.OrdinalIgnoreCase))
            return reportPath;

        // For .txt reports, look for sibling .snapshot.json
        string dir  = Path.GetDirectoryName(reportPath) ?? ".";
        string name = Path.GetFileNameWithoutExtension(reportPath);
        string snapshotPath = Path.Combine(dir, $"{name}.snapshot.json");

        if (File.Exists(snapshotPath))
            return snapshotPath;

        throw new FileNotFoundException(
            $"Could not find snapshot file for report: {reportPath}\n" +
            $"Expected: {snapshotPath}\n" +
            "Note: Only reports generated by mvc-inspect v2.6.0+ include a snapshot file.");
    }
}
